"""
ComicCraft - Layout Builder
Assembles panel titles, generated illustrations, scene descriptions,
captions, and narrations into a coherent comic layout structure.
"""

import re
from typing import List, Dict, Any, Union


def _extract_panel_sections(panel_text: str) -> Dict[str, str]:
    """Extracts caption, narration, and prompt from panel text."""
    caption = ""
    narration = ""
    prompt_ref = ""

    caption_match = re.search(r"\*\*CAPTION:\*\*\s*(.*?)(?=\*\*NARRATION:|\*\*IMAGE PROMPT:|$)", panel_text, re.DOTALL | re.IGNORECASE)
    if caption_match:
        caption = caption_match.group(1).strip()

    narration_match = re.search(r"\*\*NARRATION:\*\*\s*(.*?)(?=\*\*IMAGE PROMPT:|\*\*CAPTION:|$)", panel_text, re.DOTALL | re.IGNORECASE)
    if narration_match:
        narration = narration_match.group(1).strip()

    prompt_match = re.search(r"\*\*IMAGE PROMPT:\*\*\s*(.*?)$", panel_text, re.DOTALL | re.IGNORECASE)
    if prompt_match:
        prompt_ref = prompt_match.group(1).strip()

    return {
        "caption": caption,
        "narration": narration,
        "prompt_ref": prompt_ref
    }


def build_comic_layout(
    image_paths: List[str],
    full_story: str,
    outline: List[Union[Dict[str, Any], str]]
) -> List[Dict[str, Any]]:
    """
    Organizes generated images and comic story into a structured panel list.

    Args:
        image_paths (list): List of paths to generated panel images.
        full_story (str): Full story text generated by Gemini Pro.
        outline (list): List of panel outline dictionaries.

    Returns:
        List[Dict[str, Any]]: List of structured comic panels.
    """
    # Split the full story into individual panel segments
    raw_segments = re.split(r"(?:\*\*Panel|\*\*panel)", full_story)
    story_panels = []
    for seg in raw_segments:
        if seg.strip():
            story_panels.append(f"**Panel{seg}")

    num_panels = max(len(outline), len(image_paths), 1)

    # Pad story panels if fewer were returned
    while len(story_panels) < num_panels:
        p_num = len(story_panels) + 1
        story_panels.append(f"**Panel {p_num}: Continuing the Quest**\nThe journey surges onward with steadfast determination.\n**CAPTION:** Shadows lengthen across the land.\n**NARRATION:** \"Keep pushing forward!\" shouted the hero.")

    layout = []
    for idx in range(1, num_panels + 1):
        img_idx = idx - 1
        image_path = image_paths[img_idx] if img_idx < len(image_paths) else "static/panels/default.png"
        raw_text = story_panels[img_idx] if img_idx < len(story_panels) else ""

        panel_info = outline[img_idx] if img_idx < len(outline) else {}
        if isinstance(panel_info, dict):
            title = panel_info.get("title", f"Panel {idx}")
            scene_desc = panel_info.get("scene_description", "")
            img_prompt = panel_info.get("image_prompt", "")
        else:
            title = f"Panel {idx}"
            scene_desc = str(panel_info)
            img_prompt = str(panel_info)

        # Remove the first header line (e.g. "**Panel 1: Title**") from text body
        text_lines = raw_text.strip().splitlines()
        if text_lines and ("**panel" in text_lines[0].lower() or "panel " in text_lines[0].lower()):
            body_text = "\n".join(text_lines[1:]).strip()
        else:
            body_text = raw_text.strip()

        # Parse sections
        sections = _extract_panel_sections(body_text)

        # Normalize web image path
        norm_img_path = image_path.replace("\\", "/")
        if not norm_img_path.startswith("/") and not norm_img_path.startswith("http"):
            web_img_path = "/" + norm_img_path
        else:
            web_img_path = norm_img_path

        layout.append({
            "panel": idx,
            "title": title,
            "image_path": norm_img_path,
            "web_image_path": web_img_path,
            "text": body_text,
            "scene_description": scene_desc,
            "caption": sections["caption"],
            "narration": sections["narration"],
            "image_prompt": img_prompt or sections["prompt_ref"]
        })

    return layout
